name: Publish packages to NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: yarn run dist
      - run: cp package.json dist
      - run: cp README.md dist
      - run: cd dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
